### ISSUE TITLE
Run expression for a batch of records?

### ISSUE THREAD

**Issue by liumiaowilson** [cesarParra/expression#128]
Hi, I have a scenario that we want to enable admins to configure an expression as a criteria to filter a list of records in apex. With a batch of records, how can we run the expression against each record? If we pass in the record id as the context, then each query will be issued when running the expression and this will exceed the limit. If we pre-fetch the records and pass in the record as the context, we don't know which fields are used in the expression so that we can query. Do you have any suggestions here?

**Comment by cesarParra** [comment]
Hi @liumiaowilson 

Unfortunately that wouldn't be easily possible right now without some kind of workaround, precisely because of the reasons you mention. This is something that is high in my list of priorities to implement.
