### ISSUE TITLE
Resolving of nested custom context Map<String, Object> not working. 

### ISSUE THREAD

**Issue by gethrok** [cesarParra/expression#154]
Hi, 
I came across use case, where I want to use JSON as custom context. For example: 
```
{
  "number1": 2,
  "number2": 3,
  "nested": {
    "nestedValue": "hello",
    "nested2": {
      "nestedValue2": "hello2"
    }
  }
}
```

Then we add it to the config as:
```
Configuration config = new Configuration();
Map<String, Object> jsonDeserialized = (Map<String, Object>)JSON.deserializeUntyped(inp.exampleJson);
config.customContext = jsonDeserialized;
```

However the nested values are not resolved. So accessing for example @nested.nestedValue will result in error. I have found out, that in the Interpreter class you are resolving Map<Object,Object> however in this case it's Map<String,Object> so the exception 
"Error executing get expression: could not determine the value of:" will be fired. 
My current fix is to simply add the Map<String, Object> to the Interpreter resolution. Works fine even with multiple levels of nested values. 

```
} else if (result instanceof Map<String, Object>) {
    if (!getExpr.arguments.isEmpty()) {
        throw new Exceptions.RuntimeException(
            getExpr.field,
            'Error executing expression. Get expressions on Maps must not have arguments.'
        );
    }

    Map<String, Object> castMap = (Map<String, Object>) result;
    if (castMap.containsKey(getExpr.field.lexeme)) {
        return castMap.get(getExpr.field.lexeme);
    }

    throw new Exceptions.RuntimeException(
        getExpr.field,
        'Error executing get expression: the map does not contain a key with the name: ' + getExpr.field.lexeme
    );
}
```

**Comment by cesarParra** [comment]
Hi @gethrok 

Looks good to me!

Let me put that fix in and release a new version

**Comment by cesarParra** [comment]
Fix is in. In case of using the managed package it is in version >1.10 (04tRb000001SS2PIAW)
