### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by kvasoya224** [cesarParra/expression#160]
### Installation is failed with below error

Package: Expression (04tRb000001TfwrIAC)
Error Number: 1686169679-59139 (-1186991472)
Problem:

1. ApexClass Field does not exist: UptimeRecordStart on Asset
QInMemoryDatabaseTest: Field does not exist: UptimeRecordStart on Asset

2. ApexClass Field does not exist: UptimeRecordStart on Asset
QInMemoryDatabaseTest: Field does not exist: UptimeRecordStart on Asset

3. ApexClass Field does not exist: UptimeRecordStart on Asset
QInMemoryDatabaseTest: Field does not exist: UptimeRecordStart on Asset

4. ApexClass Field does not exist: UptimeRecordStart on Asset
QInMemoryDatabaseTest: Field does not exist: UptimeRecordStart on Asset

**Comment by cesarParra** [comment]
Thanks @kvasoya224 

I'm guessing not all orgs come with that standard field. Let me update those tests and release a version without them.

**Comment by cesarParra** [comment]
Try it out with latest package version and let me know if that works for you now.

Package version Id: `04tRb000001iDH7IAM`

**Comment by kvasoya224** [comment]
It is successfully installed, thanks @cesarParra, I am closing this issue now
