### ISSUE TITLE
TEXT() function seems to convert numbers with the dot notation before converting to text

### ISSUE THREAD

**Issue by gethrok** [cesarParra/expression#163]
![image](https://github.com/user-attachments/assets/9e639131-e2ce-42dd-9e53-2d9d3015c858)

TEXT(123456789) results in  "123.456.789"

**Comment by cesarParra** [comment]
Thanks @gethrok .

I see what the issue is, there's extra formatting going on that in this case seems to be unnecessary. I'll have a new version without that shortly

**Comment by cesarParra** [comment]
New version Id: 04tRb000001sOuPIAU
